# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/places', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('google', models.URLField(blank=True, null=True, verbose_name='Google')),
                ('linkdn', models.URLField(blank=True, null=True, verbose_name='Linkdn')),
            ],
            options={
                'verbose_name': 'Ponente',
                'verbose_name_plural': 'Ponentes',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tematicas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/tematics', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Tematica',
                'verbose_name_plural': 'Tematicas',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(related_name='events', to='events.Place', verbose_name='Lugares del evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='ponents',
            field=models.ManyToManyField(related_name='events', to='events.Ponent', verbose_name='Ponentes'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='events.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='tematics',
            field=models.ManyToManyField(related_name='events', to='events.Tematic', verbose_name='Tematicas'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='events.Event', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
