# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170517_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Place', verbose_name='Lugares del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ponents',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Ponent', verbose_name='Ponentes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tematics',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Tematic', verbose_name='Tematicas'),
        ),
    ]
