# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170518_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cancionero',
                'verbose_name_plural': 'Cancioneros',
                'ordering': ('name',),
            },
        ),
    ]
