# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 23:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170517_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='likes'),
        ),
    ]
