# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170517_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
